// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Pandora.Cli")]
[assembly: AssemblyDescriptionAttribute("Elders.Pandora")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Pandora.Cli")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("0.4.0.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.4.0-beta.1+5.Branch.release/0.4.0.Sha.c18f8d1ddbd7a4c9b6f83d7947a8d3a1b191faf4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0.0";
    }
}
