// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Pandora")]
[assembly: AssemblyDescriptionAttribute("Elders.Pandora")]
[assembly: AssemblyProductAttribute("Elders.Pandora")]
[assembly: AssemblyVersionAttribute("1.1.38")]
[assembly: AssemblyInformationalVersionAttribute("1.1.38")]
[assembly: AssemblyFileVersionAttribute("1.1.38")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.38";
    }
}
