// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Pandora")]
[assembly: AssemblyDescriptionAttribute("Elders.Pandora")]
[assembly: AssemblyProductAttribute("Elders.Pandora")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
